administracio/urls.py
from django.urls import path

from .views import usuari_edit

urlpatterns = [
    path('usuari/edit/<int:id>',
         usuari_edit, name='usuari_edit'),
    
]

bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import HomeSensePrivilegis
from moviments.views import  dashboardMoviments2

urlpatterns = [
    #path('', Home.as_view(), name='home'),
    path('', dashboardMoviments2, name='home'), 
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'), 
    
    path('sense_privilegis/', HomeSensePrivilegis.as_view(), name='sense_privilegis')
]

financesDom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('mov/', include(('mov.urls', 'mov'), namespace='mov')),
    path('moviments/', include(('moviments.urls', 'moviments'), namespace='moviments')),
    path('admin/', admin.site.urls),
    path('administracio/', include(('administracio.urls', 'mov'), namespace='administracio')),
]

mov/urls.py
from django.urls import path
#from django.contrib import admin

from .views import GrupMovimentView, GrupMovimentNew, GrupMovimentEdit, GrupMovimentDelete, grupMoviment_inactivar, \
SubgrupMovimentView, SubgrupMovimentNew, SubgrupMovimentEdit, SubgrupMovimentDelete, subgrupMoviment_inactivar, \
DetallMovimentView, DetallMovimentNew, DetallMovimentEdit, DetallMovimentDelete, detallMoviment_inactivar,  \
FormaPagamentView, FormaPagamentNew, FormaPagamentEdit, FormaPagamentDelete, formaPagament_inactivar, \
CaixaView, CaixaNew, CaixaEdit, CaixaDelete, caixa_inactivar, caixa_usuaris, caixa_usuari_canvia_estat


urlpatterns = [
    path('grupsDeMoviments/', GrupMovimentView.as_view(), name='grupMoviment_list'),
    path('grupsDeMoviments/new', GrupMovimentNew.as_view(), name='grupMoviment_new'),
    path('grupsDeMoviments/edit/<int:pk>',
         GrupMovimentEdit.as_view(), name='grupMoviment_edit'),
    path('grupsDeMoviments/delete/<int:pk>',
         GrupMovimentDelete.as_view(), name='grupMoviment_del'),
    path('grupsDeMoviments/inactivar/<int:id>',
         grupMoviment_inactivar, name='grupMoviment_inactivar'),
    
    
    path('subgrupsDeMoviments/', SubgrupMovimentView.as_view(), name='subgrupMoviment_list'),
    path('subgrupsDeMoviments/new', SubgrupMovimentNew.as_view(), name='subgrupMoviment_new'),
    path('subgrupsDeMoviments/edit/<int:pk>',
         SubgrupMovimentEdit.as_view(), name='subgrupMoviment_edit'),
    path('subgrupsDeMoviments/delete/<int:pk>',
         SubgrupMovimentDelete.as_view(), name='subgrupMoviment_del'),
    path('subgrupsDeMoviments/inactivar/<int:id>',
         subgrupMoviment_inactivar, name='subgrupMoviment_inactivar'),
    
    
    path('detallsDeMoviments/', DetallMovimentView.as_view(), name='detallMoviment_list'),
    path('detallsDeMoviments/new', DetallMovimentNew.as_view(), name='detallMoviment_new'),
    path('detallsDeMoviments/edit/<int:pk>',
         DetallMovimentEdit.as_view(), name='detallMoviment_edit'),
    path('detallsDeMoviments/delete/<int:pk>',
         DetallMovimentDelete.as_view(), name='detallMoviment_del'),
    path('detallsDeMoviments/inactivar/<int:id>',
         detallMoviment_inactivar, name='detallMoviment_inactivar'),
    
    
    path('formaPagaments/', FormaPagamentView.as_view(), name='formaPagament_list'),
    path('formaPagaments/new', FormaPagamentNew.as_view(), name='formaPagament_new'),
    path('formaPagaments/edit/<int:pk>',
         FormaPagamentEdit.as_view(), name='formaPagament_edit'),
    path('formaPagaments/delete/<int:pk>',
         FormaPagamentDelete.as_view(), name='formaPagament_del'),
    path('formaPagaments/inactivar/<int:id>',
         formaPagament_inactivar, name='formaPagament_inactivar'),
    
    
    path('caixes/', CaixaView.as_view(), name='caixa_list'),
    path('caixes/new', CaixaNew.as_view(), name='caixa_new'),
    path('caixes/edit/<int:pk>',
         CaixaEdit.as_view(), name='caixa_edit'),
    path('caixes/delete/<int:pk>',
         CaixaDelete.as_view(), name='caixa_del'),
    path('caixes/inactivar/<int:id>',
         caixa_inactivar, name='caixa_inactivar'),    
    path('caixes/usuaris/<int:id>',
         caixa_usuaris, name='caixa_usuaris'),
    path('caixes/usuarisestat/<int:id>',
         caixa_usuari_canvia_estat, name='caixa_canvia_estat'),               
]

moviments/urls.py
from django.urls import path
from django.conf.urls import url
#from django.contrib import admin

from .views import MovimentView, MovimentNew, MovimentEdit,  MovimentDelete, movimentDuplicate,\
     dashboardMoviments2, treeMapDespesa, dashboardSaldo, dashboardDespesa


urlpatterns = [
    path('moviment/', MovimentView.as_view(), name='moviment_list'),
    path('moviment/new', MovimentNew.as_view(), name='moviment_new'),
    path('moviment/edit/<int:pk>',MovimentEdit.as_view(), name='moviment_edit'),
    path('moviment/delete/<int:pk>',  MovimentDelete.as_view(), name='moviment_del'),
    path('moviment/duplicate/<int:id>', movimentDuplicate, name='moviment_duplicate'),
    
    path('moviment/dashboard/<int:year>', dashboardMoviments2, name='moviment_dash'),
    path('moviment/dashboard',  dashboardMoviments2, name='moviment_dash'),
    path('moviment/dashboardtree/<int:year>', treeMapDespesa, name='moviment_tree'),
    path('moviment/dashboardtree', treeMapDespesa, name='moviment_tree'),
    url('moviment/dashboardtree/(?P<dataInici>\d{4}-\d{2}-\d{2})/(?P<dataFi>\d{4}-\d{2}-\d{2})', treeMapDespesa, name='moviment_tree'),
    
    
    path('moviment/dashboardsaldo', dashboardSaldo, name='dashboard_saldo'),
    path('moviment/dashboardsaldo/<int:year>/<int:month>', dashboardSaldo, name='dashboard_saldo'),
    
    
    path('moviment/dashboarddespesa', dashboardDespesa, name='dashboard_despesa'),
    path('moviment/dashboarddespesa/<int:year>/<int:month>', dashboardDespesa, name='dashboard_despesa'),
    
    #path('moviment/dashboardtree/^(<dateStart>\d{4}-\d{2}-\d{2})/^(<dateEnd>\d{4}-\d{2}-\d{2})', treeMapDespesa, name='moviment_tree'),
    
    
    
    #url(r'^(?P<date>\d{4}-\d{2}-\d{2})/$', views.index, name='index'),
 ]

moviments/models.py
from django.db import models

from bases.models import ClasseBase
from mov.models import DetallMoviment, Caixa, FormaPagament



class Moviment(ClasseBase):
    detallMoviment = models.ForeignKey(DetallMoviment, on_delete=models.PROTECT)
    caixa = models.ForeignKey(Caixa, on_delete=models.PROTECT)
    formaPagament = models.ForeignKey(FormaPagament, on_delete=models.PROTECT)
    valor = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        help_text='Valor del moviment'
        )
    dataMoviment = models.DateField(
        help_text='Data del moviment'
        )

    def __str__(self):
        return '{}:{}:{}:{}:::{}'.format(self.detallMoviment.subgrupMoviment.grupMoviment.descripcio, self.detallMoviment.subgrupMoviment.descripcio, self.detallMoviment.descripcio, self.dataMoviment , self.valor)
    
    def save(self):
        super(Moviment, self).save()

    def copy(self):
        movmimentNew = Moviment()
        movmimentNew.detallMoviment=self.detallMoviment
        movmimentNew.caixa=self.caixa
        movmimentNew.formaPagament=self.formaPagament
        return movmimentNew

    class Meta:
        #ordering = ["-dataMoviment"]
        verbose_name_plural = "Moviments"
        unique_together = ('dataMoviment', 'detallMoviment', 'formaPagament', 'caixa')
        
    

templates/base/base.html
{%load static %}
<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Finances</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'base/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

  <!-- jQuery confirm-->
  <link href="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.css' %}" rel="stylesheet">

   <!-- XDSoft DateTimePicker -->  
   <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />-->  
   <link href="{% static 'base/css/jquery.datetimepicker.min.css' %}" rel="stylesheet">

   <!-- chart -->
   <link href="{% static 'base/css/Chart.min.css' %}" rel="stylesheet">
   
   <!--  select2  -->
   <link href="{% static 'base/css/select2.min.css' %}" rel="stylesheet" /> 
   
   

</head>

<body id="page-top" class="bg-gradient-primary">


   {% block side_bar %} 
  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'bases:home' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fab fa-creative-commons-nc-eu"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Finances <sup>2</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'moviments:moviment_dash'%} ">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Menú
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Catàlegs</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Catàleg de moviments:</h6>
            {% if perms.mov.view_grupmoviment %}
            <a class="collapse-item" href="{% url 'mov:grupMoviment_list' %}">Grups de moviments</a>
            {% endif %}
            {% if perms.mov.view_subgrupmoviment %}
            <a class="collapse-item" href="{% url 'mov:subgrupMoviment_list' %}">Subgrups de moviments</a>
            {% endif %}
            {% if perms.mov.view_detallmoviment %}
            <a class="collapse-item" href="{% url 'mov:detallMoviment_list' %}">Detall de moviments</a>
            {% endif %}
          </div>
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Catàleg de caixes:</h6>
                       
            {% if perms.mov.view_formapagament %}
            <a class="collapse-item" href="{% url 'mov:formaPagament_list' %}">Formes de pagament</a>
            {% endif %}
            {% if perms.mov.view_caixa %}
            <a class="collapse-item" href="{% url 'mov:caixa_list' %}">Caixes</a>
            {% endif %}
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMoviments" aria-expanded="true" aria-controls="collapseMoviments">
          <i class="fas fa-fw fa-truck"></i>
          <span>Moviments</span>
        </a>
        <div id="collapseMoviments" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Moviments:</h6>
            {% if perms.moviments.view_moviment %}
            <a class="collapse-item" href="{% url 'moviments:moviment_list' %}">Moviments</a>
            {% endif %}
            

          </div>
        </div>
      </li>
    

	 <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAnalisis" aria-expanded="true" aria-controls="collapseAnalisis">
          <i class="fas fa-fw fa-chart-bar"></i>
          <span>An&agrave;lisi</span>
        </a>
        <div id="collapseAnalisis" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">An&agrave;lisi</h6>
            	<a class="collapse-item" href="{% url 'moviments:dashboard_despesa' %}">Despeses</a>
            	<a class="collapse-item" href="{% url 'moviments:moviment_tree' %}">Arbre despeses</a>
            	<a class="collapse-item" href="{% url 'moviments:dashboard_saldo' %}">Saldo</a>
            
            

          </div>
        </div>
      </li>

     

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    </ul>
    {% endblock side_bar %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% block top_bar %}
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

       
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

         

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.username }}</span>
                <!--<img class="img-profile rounded-circle" src="">-->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#" onclick="obrir_modal('{% url 'administracio:usuari_edit' user.id %}')">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        {% endblock top_bar %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        {% block page_content %}
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

        </div>
        {% endblock page_content %}
        <!-- /.container-fluid -->
        {% block footer %}
      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      
      <!--<footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>-->
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  {% endblock footer %}
  <!-- End of Page Wrapper -->

  {% block login %}{% endblock login %}

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Tancar la sessi&oacute; per {{user.username}}?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Selecciona "Tancar sessió" per sortir de l'usuari  {{user.username}}</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel&middot;lar</button>
          <a class="btn btn-primary" href="{%url 'bases:logout'  %}">Tancar sessió</a>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="popup"></div>

	
   

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'base/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.js' %}"></script>

   


  <!-- Core plugin JavaScript-->
  <script src="{% static 'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'base/js/sb-admin-2.min.js' %}"></script>

	<!-- Page level plugins -->
	<script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
	
	
	<script src="{% static  'base/js/jquery.chained.min.js' %}"></script>
	
	<!--  chart -->
	<script src="{% static  'base/js/Chart.min.js' %}"></script>
	<script src="{% static  'base/js/Chart.bundle.min.js' %}"></script>
	<script src="{% static  'base/js/plotly-latest.min.js' %}"></script>
	
	
	<!--  color and datetime pickers -->
	<script src="{% static  'base/js/jqColorPicker.min.js' %}"></script>
	<script src="{% static  'base/js/jquery.datetimepicker.full.min.js' %}"></script>
	
	
<!-- 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>  
   <script  type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tinyColorPicker/1.1.1/jqColorPicker.min.js"></script>  
    -->
    
    <script src="{% static  'base/js/select2.min.js' %}"></script>

 
<script>
  $(document).ready(function () {
    jQuery.datetimepicker.setLocale('ca');
  });
</script>

  {% block control_modal %}
  <script>
    function obrir_modal(url)
    {
      $("#popup").load(url, function(){
        $(this).modal({
          backdrop:'static',
          keyboard: false
        })
        $(this).modal('show');
      });
      return false;
    }

    
    
    
    
    function tancar_modal()
    {
      $('#popup').modal('hide');
      return false;
    }


    function mensaje(msg,color='red')
    {
      var msg2 = msg.substr(0,msg.indexOf(']'));
      m = msg2.match(/\[(.*)/);
      missatge = m[1]
	  if (color=="success")
      {
        color="green";
      }
      if (color=="error")
      {
        color="red";
      }

      $.alert({
        title:'',
        theme:'material',
        type:color,
        content:missatge
      });
    }

    {% if messages %}
      {% for message in messages %}
        console.log("{{ message.tags }}");
        mensaje("{{ message }}","{{ message.tags }}");
      {% endfor %}
    {% endif %}
    
    
  </script>
  {% endblock control_modal %}
  {% block js_page %} {% endblock js_page %}

</body>

</html>

templates/base/inactivar.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
		<form method="POST" class="form-inline">
		    {% csrf_token %}
		    <div class="col-xl-12 col-md-6 mb-6">
		        <div class="card border-left-warning shadow h-100 py-2">
		          <div class="card-body">
		            <div class="row no-gutters align-items-center">
		              <div class="col mr-4">
		                <div class="text-xs font-weight-bold text-warning text-uppercase mb-2">Desactivar {{ obj.descripcio }}?</div>
		                <button type="button" class="btn btn-danger" id="btnInactivar"><i class="far fa-question-circle"></i> Sí, desactivar</button>
		                <button type="button" class="btn btn-success" onclick="return tancar_modal()"> Cancel·lar </button>
		              </div>
		              <div class="col-auto">
		                <i class="fas fa-question-circle fa-2x text-gray-300"></i>
		              </div>
		            </div>
		          </div>
		        </div>
		      </div>
		</form>
	</div>
</diV>

 {% block js_page_inactiv %} {% endblock js_page_inactiv %}