financesDom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('mov/', include(('mov.urls', 'mov'), namespace='mov')),
    path('moviments/', include(('moviments.urls', 'moviments'), namespace='moviments')),
    path('admin/', admin.site.urls),
    path('administracio/', include(('administracio.urls', 'mov'), namespace='administracio')),
]

mov/urls.py
from django.urls import path
#from django.contrib import admin

from .views import GrupMovimentView, GrupMovimentNew, GrupMovimentEdit, GrupMovimentDelete, grupMoviment_inactivar, \
SubgrupMovimentView, SubgrupMovimentNew, SubgrupMovimentEdit, SubgrupMovimentDelete, subgrupMoviment_inactivar, \
DetallMovimentView, DetallMovimentNew, DetallMovimentEdit, DetallMovimentDelete, detallMoviment_inactivar,  \
FormaPagamentView, FormaPagamentNew, FormaPagamentEdit, FormaPagamentDelete, formaPagament_inactivar, \
CaixaView, CaixaNew, CaixaEdit, CaixaDelete, caixa_inactivar, caixa_usuaris, caixa_usuari_canvia_estat


urlpatterns = [
    path('grupsDeMoviments/', GrupMovimentView.as_view(), name='grupMoviment_list'),
    path('grupsDeMoviments/new', GrupMovimentNew.as_view(), name='grupMoviment_new'),
    path('grupsDeMoviments/edit/<int:pk>',
         GrupMovimentEdit.as_view(), name='grupMoviment_edit'),
    path('grupsDeMoviments/delete/<int:pk>',
         GrupMovimentDelete.as_view(), name='grupMoviment_del'),
    path('grupsDeMoviments/inactivar/<int:id>',
         grupMoviment_inactivar, name='grupMoviment_inactivar'),
    
    
    path('subgrupsDeMoviments/', SubgrupMovimentView.as_view(), name='subgrupMoviment_list'),
    path('subgrupsDeMoviments/new', SubgrupMovimentNew.as_view(), name='subgrupMoviment_new'),
    path('subgrupsDeMoviments/edit/<int:pk>',
         SubgrupMovimentEdit.as_view(), name='subgrupMoviment_edit'),
    path('subgrupsDeMoviments/delete/<int:pk>',
         SubgrupMovimentDelete.as_view(), name='subgrupMoviment_del'),
    path('subgrupsDeMoviments/inactivar/<int:id>',
         subgrupMoviment_inactivar, name='subgrupMoviment_inactivar'),
    
    
    path('detallsDeMoviments/', DetallMovimentView.as_view(), name='detallMoviment_list'),
    path('detallsDeMoviments/new', DetallMovimentNew.as_view(), name='detallMoviment_new'),
    path('detallsDeMoviments/edit/<int:pk>',
         DetallMovimentEdit.as_view(), name='detallMoviment_edit'),
    path('detallsDeMoviments/delete/<int:pk>',
         DetallMovimentDelete.as_view(), name='detallMoviment_del'),
    path('detallsDeMoviments/inactivar/<int:id>',
         detallMoviment_inactivar, name='detallMoviment_inactivar'),
    
    
    path('formaPagaments/', FormaPagamentView.as_view(), name='formaPagament_list'),
    path('formaPagaments/new', FormaPagamentNew.as_view(), name='formaPagament_new'),
    path('formaPagaments/edit/<int:pk>',
         FormaPagamentEdit.as_view(), name='formaPagament_edit'),
    path('formaPagaments/delete/<int:pk>',
         FormaPagamentDelete.as_view(), name='formaPagament_del'),
    path('formaPagaments/inactivar/<int:id>',
         formaPagament_inactivar, name='formaPagament_inactivar'),
    
    
    path('caixes/', CaixaView.as_view(), name='caixa_list'),
    path('caixes/new', CaixaNew.as_view(), name='caixa_new'),
    path('caixes/edit/<int:pk>',
         CaixaEdit.as_view(), name='caixa_edit'),
    path('caixes/delete/<int:pk>',
         CaixaDelete.as_view(), name='caixa_del'),
    path('caixes/inactivar/<int:id>',
         caixa_inactivar, name='caixa_inactivar'),    
    path('caixes/usuaris/<int:id>',
         caixa_usuaris, name='caixa_usuaris'),
    path('caixes/usuarisestat/<int:id>',
         caixa_usuari_canvia_estat, name='caixa_canvia_estat'),               
]

moviments/urls.py
from django.urls import path
from django.conf.urls import url
#from django.contrib import admin

from .views import MovimentView, MovimentNew, MovimentEdit,  MovimentDelete, movimentDuplicate,\
     dashboardMoviments2, treeMapDespesa, dashboardSaldo, dashboardDespesa


urlpatterns = [
    path('moviment/', MovimentView.as_view(), name='moviment_list'),
    path('moviment/new', MovimentNew.as_view(), name='moviment_new'),
    path('moviment/edit/<int:pk>',MovimentEdit.as_view(), name='moviment_edit'),
    path('moviment/delete/<int:pk>',  MovimentDelete.as_view(), name='moviment_del'),
    path('moviment/duplicate/<int:id>', movimentDuplicate, name='moviment_duplicate'),
    
    path('moviment/dashboard/<int:year>', dashboardMoviments2, name='moviment_dash'),
    path('moviment/dashboard',  dashboardMoviments2, name='moviment_dash'),
    path('moviment/dashboardtree/<int:year>', treeMapDespesa, name='moviment_tree'),
    path('moviment/dashboardtree', treeMapDespesa, name='moviment_tree'),
    url('moviment/dashboardtree/(?P<dataInici>\d{4}-\d{2}-\d{2})/(?P<dataFi>\d{4}-\d{2}-\d{2})', treeMapDespesa, name='moviment_tree'),
    
    
    path('moviment/dashboardsaldo', dashboardSaldo, name='dashboard_saldo'),
    path('moviment/dashboardsaldo/<int:year>/<int:month>', dashboardSaldo, name='dashboard_saldo'),
    
    
    path('moviment/dashboarddespesa', dashboardDespesa, name='dashboard_despesa'),
    path('moviment/dashboarddespesa/<int:year>/<int:month>', dashboardDespesa, name='dashboard_despesa'),
    
    #path('moviment/dashboardtree/^(<dateStart>\d{4}-\d{2}-\d{2})/^(<dateEnd>\d{4}-\d{2}-\d{2})', treeMapDespesa, name='moviment_tree'),
    
    
    
    #url(r'^(?P<date>\d{4}-\d{2}-\d{2})/$', views.index, name='index'),
 ]

moviments/models.py
from django.db import models

from bases.models import ClasseBase
from mov.models import DetallMoviment, Caixa, FormaPagament



class Moviment(ClasseBase):
    detallMoviment = models.ForeignKey(DetallMoviment, on_delete=models.PROTECT)
    caixa = models.ForeignKey(Caixa, on_delete=models.PROTECT)
    formaPagament = models.ForeignKey(FormaPagament, on_delete=models.PROTECT)
    valor = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        help_text='Valor del moviment'
        )
    dataMoviment = models.DateField(
        help_text='Data del moviment'
        )

    def __str__(self):
        return '{}:{}:{}:{}:::{}'.format(self.detallMoviment.subgrupMoviment.grupMoviment.descripcio, self.detallMoviment.subgrupMoviment.descripcio, self.detallMoviment.descripcio, self.dataMoviment , self.valor)
    
    def save(self):
        super(Moviment, self).save()

    def copy(self):
        movmimentNew = Moviment()
        movmimentNew.detallMoviment=self.detallMoviment
        movmimentNew.caixa=self.caixa
        movmimentNew.formaPagament=self.formaPagament
        return movmimentNew

    class Meta:
        #ordering = ["-dataMoviment"]
        verbose_name_plural = "Moviments"
        unique_together = ('dataMoviment', 'detallMoviment', 'formaPagament', 'caixa')
        
    

moviments/views.py
import copy
import datetime
from decimal import Decimal
from dateutil.relativedelta import relativedelta

from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q, Sum, Min
from django.db.models.functions import ExtractMonth
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic


from django.template.defaulttags import register

from bases.views import SensePrivilegis
from mov.models import GrupMoviment, SubgrupMoviment, DetallMoviment, Caixa

from .forms import MovimentForm
from .models import Moviment

from bases import master 
from django.db.models.functions.datetime import ExtractYear




# classes base
class ViewBaseNew(SuccessMessageMixin, SensePrivilegis, generic.CreateView):
    context_object_name = "obj"
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    
    
class ViewBaseEdit(SuccessMessageMixin, SensePrivilegis, generic.UpdateView):
    context_object_name = "obj"
    
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
    
    
class MovimentView(SensePrivilegis, generic.ListView):
    permission_required = "moviments.view_moviment"
    model = Moviment
    template_name = "moviment/moviment_list.html"
    context_object_name = "obj"
    
    def get_queryset(self):
        return Moviment.objects.select_related('caixa').select_related('detallMoviment__subgrupMoviment__grupMoviment').select_related('formaPagament').filter(usuariCreacio=self.request.user)

    
class MovimentNew(ViewBaseNew):
    permission_required = "moviments.add_moviment"
    model = Moviment
    template_name = "moviment/moviment_form.html"
    form_class = MovimentForm
    success_url = reverse_lazy("moviments:moviment_list")

    def get_context_data(self, **kwargs):
        context = super(MovimentNew, self).get_context_data(**kwargs)
        context["grupsMoviment"] = GrupMoviment.objects.all().order_by("descripcio")
        context["subgrupsMoviment"] = SubgrupMoviment.objects.all().order_by("descripcio")
        context["detallsMoviment"] = DetallMoviment.objects.all().order_by("descripcio")
        context["caixes"] =[]
        for c in Caixa.objects.all():
            if c.usuaris.filter(username= self.request.user).count()>0:
                context["caixes"].append(c)
        
        return context
    
    
    
class MovimentEdit(ViewBaseEdit):
    permission_required = "moviments.change_moviment"
    model = Moviment
    template_name = "moviment/moviment_form.html"
    form_class = MovimentForm
    success_url = reverse_lazy("moviments:moviment_list")
    
    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        context = super(MovimentEdit, self).get_context_data(**kwargs)
        context["grupsMoviment"] = GrupMoviment.objects.all().order_by("descripcio")
        context["subgrupsMoviment"] = SubgrupMoviment.objects.all().order_by("descripcio")
        context["detallsMoviment"] = DetallMoviment.objects.all().order_by("descripcio")
        
        context["caixes"] =[]
        for c in Caixa.objects.all():
            if c.usuaris.filter(username= self.request.user).count()>0:
                context["caixes"].append(c)
        context["obj"] = Moviment.objects.filter(pk=pk).first()
        return context


class MovimentDelete(SuccessMessageMixin, generic.DeleteView):
    permission_required = "move.delete_moviment"
    model = Moviment
    template_name = 'moviment/moviment_del.html'
    context_object_name = 'obj'
    success_url = reverse_lazy("moviments:moviment_list")
    success_message = "Moviment eliminat correctament"
 
 
@login_required(login_url='/login/')
@permission_required('moviments.add_moviment', login_url='bases:sin_privilegios')
def movimentDuplicate(request, id):
    moviment = Moviment.objects.filter(pk=id).first()
    contexto={}
    form_class = MovimentForm
    movimentNew = Moviment.copy(moviment)
    
    contexto["grupsMoviment"] = GrupMoviment.objects.all().order_by("descripcio")
    contexto["subgrupsMoviment"] = SubgrupMoviment.objects.all().order_by("descripcio")
    contexto["detallsMoviment"] = DetallMoviment.objects.all().order_by("descripcio")
    
    template_name="moviment/moviment_form.html"
    if not moviment:
        return redirect("moviments:moviment_list")
    if request.method=='GET':
        #contexto={'obj':movimentNew, 'dup':True, 'form':form_class}
        contexto["obj"]=movimentNew
        contexto["dup"]= True
        contexto["form"]=form_class
    if request.method=='POST':
        moviment.save()
        return redirect("moviments:moviment_list")
    return render(request,template_name,contexto)    
    
'''   
@login_required(login_url='/login/')
def dashboardMoviments(request, year):
    
    tree = treeMapDespesa(request, year)
    
    # balanç (ingres-despesa)
    balanc = Moviment.objects.filter(Q(usuariCreacio__username=request.user) &  Q(dataMoviment__year=year)  & ~Q(detallMoviment__subgrupMoviment__grupMoviment__descripcio__exact='TRASPÀS COMPTES')   & ~Q(detallMoviment__descripcio__exact='SALDO INICIAL')   & ~Q(formaPagament__descripcio='DESPESA ADELA') ).annotate(month=ExtractMonth('dataMoviment')).values('month').annotate(total=Sum('valor'))
    #saldo
    saldo = piesaldo(request)
    
    # despesa  mensual (eliminant els positius)
    despesamensual = Moviment.objects.filter(Q(usuariCreacio__username=request.user) & Q(dataMoviment__year=year) & Q(valor__lt=0) & ~Q(detallMoviment__subgrupMoviment__grupMoviment__descripcio__exact='TRASPÀS COMPTES')).annotate(month=ExtractMonth('dataMoviment')).values('month', 'detallMoviment__subgrupMoviment__grupMoviment__descripcio').annotate(total=-Sum('valor'))
    # ingrés mensual (tots els positius)
    ingresmensual = Moviment.objects.filter(Q(usuariCreacio__username=request.user) & Q(dataMoviment__year=year) & Q(valor__gt=0) & ~Q(detallMoviment__subgrupMoviment__grupMoviment__descripcio__exact='TRASPÀS COMPTES')   & ~Q(detallMoviment__descripcio__exact='SALDO INICIAL')).annotate(month=ExtractMonth('dataMoviment')).values('month', 'detallMoviment__subgrupMoviment__grupMoviment__descripcio').annotate(total=Sum('valor'))
    
    labels = list(range(1, 13))  # inicialitzem amb els 12 mesos
    vBalanc = [0] * 12
    for x in balanc:
        vBalanc[int(x['month']) - 1] = float(x['total'])
    grupsMoviment = list(GrupMoviment.objects.all().values('descripcio', 'color'))
    vDespesa = {}
    for x in grupsMoviment:
        vDespesa[x['descripcio']] = [[x['color']],[0] * 12]
        
    vIngres = copy.deepcopy(vDespesa)
    
    for x in despesamensual:
        vDespesa[x['detallMoviment__subgrupMoviment__grupMoviment__descripcio']][1][int(x['month']) - 1] = float(x['total'])
   
    
    for x in ingresmensual:
        vIngres[x['detallMoviment__subgrupMoviment__grupMoviment__descripcio']][1][int(x['month']) - 1] = float(x['total'])
    
    m = list(Moviment.objects.filter(Q(dataMoviment__year=year))
        .values('detallMoviment__subgrupMoviment__grupMoviment__descripcio').annotate(total=Sum('valor'))
        )
    labels2 = [] 
    values2 = []
    for x in m:
        labels2.append(x['detallMoviment__subgrupMoviment__grupMoviment__descripcio'])  
        values2.append(float(x['total']))
        
    
    
    context = {}
    template_name = "moviment/moviment_dashboard.html"
        
    if request.method == 'GET':
        context = { 'mesLabels':labels, 'vBalanc':vBalanc, 'vDespesa':vDespesa, 'vIngres':vIngres,
                   'saldoLabel':saldo[0], 'saldoColor':saldo[1], 'saldoValues': saldo[2],
                   'treeLabels':tree[0],'treeParents':tree[1], 'treeValues':tree[2], 'treeText':tree[3], 'treeColor': tree[4]
                   }
        
    # if request.method=='POST':
        
        # messages.success(request, 'Grup de moviment desactivat')
        # return redirect("mov:grupMoviment_list")
    return render(request, template_name, context)   
''' 

def piesaldo(request):
    saldo = Moviment.objects.\
        filter(Q(usuariCreacio__username=request.user)  & ~Q(detallMoviment__descripcio__exact='SALDO ESTATIC')   & ~Q(formaPagament__descripcio='DESPESA ADELA') ).\
        values('caixa__descripcio').\
        annotate(total=Sum('valor'), col=Min('caixa__color'))
    saldoLabel = []
    saldoValues = []
    saldoColor = []
    for x in saldo:
        saldoLabel.append(x['caixa__descripcio'])
        saldoValues.append(float(x['total']))
        saldoColor.append(x['col'])
    return [saldoLabel, saldoColor, saldoValues]

@login_required(login_url='/login/')
def treeMapDespesa(request, dataInici=str(master.firstDateCurrentYear), dataFi=str(master.lastDateCurrentYear)):

           
    grupsMoviment = list(GrupMoviment.objects.all().values('descripcio', 'color','id'))
    subgrupsMoviment = list(SubgrupMoviment.objects.all().values('descripcio','grupMoviment__descripcio','id'))
    detallsMoviment = list(DetallMoviment.objects.all().values('descripcio', 'subgrupMoviment__descripcio', 'subgrupMoviment__grupMoviment__descripcio', 'id'))
    
    val = Moviment.objects.filter(Q(usuariCreacio__username=request.user) & Q(dataMoviment__gte=dataInici)  & Q(dataMoviment__lte=dataFi)   & ~Q(detallMoviment__subgrupMoviment__grupMoviment__descripcio__exact='TRASPÀS COMPTES')   & ~Q(detallMoviment__descripcio__exact='SALDO INICIAL')  ).values('detallMoviment__id').annotate(total=Sum('valor'))
    dval ={}
    for x in val:
        dval[x['detallMoviment__id']]=float(x['total'])
    

moviments/templates/moviment/moviment_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-lg font-weight-bold text-warning text-uppercase mb-1">Eliminar {{ obj }}?</div>
                <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Sí, eliminar</button>
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo">Cancel·lar</span></a>
              </div>
              <div class="col-auto">
                <i class="fas fa-question-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</form>
{% endblock page_content %}
{%block js_page %}
{% endblock js_page %}

moviments/templates/moviment/moviment_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        
        	{% if dup %}
        			<form method="POST" role="form" class="form-inline" action="{% url 'moviments:moviment_new' %}" >
        	{% else %}
                	<form method="POST" role="form" class="form-inline" action="{% url 'moviments:moviment_edit' obj.pk %}" >
            {% endif %}
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'moviments:moviment_new' %}" >
        {% endif %}
         {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-info shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} {% if dup %}Duplicar {% else %}Editar {% endif %}{% else %} Nou {% endif %} moviment
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6"><label for="id_dataMoviment">Data mov.</label></div>
                                {{form.dataMoviment}}
                            </div>
                            
                            
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.valor.label}}</div>
                                <div class="col-md-6">{{form.valor}}</div>    
                            </div>                            
                        </div>
                       
                       <div class="row">
                           <div class="col-md-6">
                                <div class="col-md-12">{{form.caixa.label}}</div>
                               	<div class="col-md-6">{{form.caixa}}</div>    
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-12">{{form.formaPagament.label}}</div>
                                <div class="col-md-6">{{form.formaPagament}}</div>    
                            </div>                            
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">Grup</div>
                                <div class="col-md-6">
                                    <select name="grupMoviment" id="id_grupMoviment" class="form-control from-control-sm">
                                        {% for item in grupsMoviment %}
                                        <option value="{{item.id}}">{{item.descripcio}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>
						</div>
						<div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">Subgrup</div>
                                <div class="col-md-6">
                                    <select name="subgrupMoviment" id="id_subgrupMoviment" class="form-control from-control-sm">
                                        {% for item in subgrupsMoviment %}
                                        <option value="{{item.id}}"  data-chained="{{item.grupMoviment.id}}">{{item.descripcio}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>                           
                        </div>

						<div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">Detall</div>
                                <div class="col-md-6">
                                    <select name="detallMoviment" id="id_detallMoviment" class="form-control from-control-sm"  style="width:250px;">
                                        {% for item in detallsMoviment %}
                                        <option value="{{item.id}}"  data-chained="{{item.subgrupMoviment.id}}">{{item.descripcio}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>
                        </div>


                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Salvar</button>
                                <button type="button" class="btn btn-success" onclick="return tancar_modal()">
                                    Cancel·lar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>

    
    $(function () {
    	$('#id_detallMoviment').select2({
            placeholder: "Seleccioni detall de moviment",
            allowClear: true,
            tags: true
        });

    	
    	$("#id_grupMoviment").val("{{ obj.detallMoviment.subgrupMoviment.grupMoviment.id }}").change();
    	$("#id_subgrupMoviment").val("{{ obj.detallMoviment.subgrupMoviment.id }}").change();
    	$("#id_detallMoviment").val("{{ obj.detallMoviment.id }}").change();
    	$("#id_subgrupMoviment").chained("#id_grupMoviment");
    	$("#id_detallMoviment").chained("#id_subgrupMoviment");
        
    	   	
    	$("#id_caixa").val("{{ obj.caixa.id }}").change();
    	$("#id_formaPagament").val("{{ obj.formaPagament.id }}").change();
    	
    	
    	$("#id_dataMoviment").datetimepicker({
            format: 'Y-m-d',
            timepicker:false
        });


    	
    	
    });
    
</script>

moviments/templates/moviment/moviment_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Moviments</h6>
      <div class="dropdown no-arrow">
        <a onclick="return obrir_modal('{% url 'moviments:moviment_new' %}')" href="#" class="btn btn-success btn-circle" role="button" ><i class="fa fa-plus"> </i></a>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hi ha moviments</div>
        {%else %}
        <table class="table table-striped table-hover">
            <thead>
            	<th>Data</th>
            	<th>Grup</th>
            	<th>Subgrup</th>
                <th>Descripcioacute;</th>
                <th>Caixa</th>
                <th>Forma pagament</th>
                <th>Valor</th>
                <th class="all">Accions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                	<td>{{item.dataMoviment|date:"Y/m/d"}}</td>
                	<td>{{item.detallMoviment.subgrupMoviment.grupMoviment}}</td>
                	<td>{{item.detallMoviment.subgrupMoviment}}</td>
                    <td>{{item.detallMoviment}}</td>
                    <td>{{item.caixa}}</td>
                    <td>{{item.formaPagament}}</td>
                    <td>{{item.valor}} &euro;</td>
                    
                    <td>
                        <button class="btn btn-info btn-circle" onclick="return obrir_modal('{% url 'moviments:moviment_edit' item.id %}')"><i class="far fa-edit"></i></button>  
                        <button class="btn btn-primary btn-circle" onclick="return obrir_modal('{% url 'moviments:moviment_duplicate' item.id %}')"><i class="fa fa-copy"></i></button>
                        <a href="{% url 'moviments:moviment_del' item.id %}" class="btn btn-danger btn-circle" role="button" ><i class="far fa-trash-alt"> </i></a>  
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock page_content %}

{% block js_page %}
<script>
  //Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}