financesDom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('mov/', include(('mov.urls', 'mov'), namespace='mov')),
    path('moviments/', include(('moviments.urls', 'moviments'), namespace='moviments')),
    path('admin/', admin.site.urls),
    path('administracio/', include(('administracio.urls', 'mov'), namespace='administracio')),
]

mov/urls.py
from django.urls import path
#from django.contrib import admin

from .views import GrupMovimentView, GrupMovimentNew, GrupMovimentEdit, GrupMovimentDelete, grupMoviment_inactivar, \
SubgrupMovimentView, SubgrupMovimentNew, SubgrupMovimentEdit, SubgrupMovimentDelete, subgrupMoviment_inactivar, \
DetallMovimentView, DetallMovimentNew, DetallMovimentEdit, DetallMovimentDelete, detallMoviment_inactivar,  \
FormaPagamentView, FormaPagamentNew, FormaPagamentEdit, FormaPagamentDelete, formaPagament_inactivar, \
CaixaView, CaixaNew, CaixaEdit, CaixaDelete, caixa_inactivar, caixa_usuaris, caixa_usuari_canvia_estat


urlpatterns = [
    path('grupsDeMoviments/', GrupMovimentView.as_view(), name='grupMoviment_list'),
    path('grupsDeMoviments/new', GrupMovimentNew.as_view(), name='grupMoviment_new'),
    path('grupsDeMoviments/edit/<int:pk>',
         GrupMovimentEdit.as_view(), name='grupMoviment_edit'),
    path('grupsDeMoviments/delete/<int:pk>',
         GrupMovimentDelete.as_view(), name='grupMoviment_del'),
    path('grupsDeMoviments/inactivar/<int:id>',
         grupMoviment_inactivar, name='grupMoviment_inactivar'),
    
    
    path('subgrupsDeMoviments/', SubgrupMovimentView.as_view(), name='subgrupMoviment_list'),
    path('subgrupsDeMoviments/new', SubgrupMovimentNew.as_view(), name='subgrupMoviment_new'),
    path('subgrupsDeMoviments/edit/<int:pk>',
         SubgrupMovimentEdit.as_view(), name='subgrupMoviment_edit'),
    path('subgrupsDeMoviments/delete/<int:pk>',
         SubgrupMovimentDelete.as_view(), name='subgrupMoviment_del'),
    path('subgrupsDeMoviments/inactivar/<int:id>',
         subgrupMoviment_inactivar, name='subgrupMoviment_inactivar'),
    
    
    path('detallsDeMoviments/', DetallMovimentView.as_view(), name='detallMoviment_list'),
    path('detallsDeMoviments/new', DetallMovimentNew.as_view(), name='detallMoviment_new'),
    path('detallsDeMoviments/edit/<int:pk>',
         DetallMovimentEdit.as_view(), name='detallMoviment_edit'),
    path('detallsDeMoviments/delete/<int:pk>',
         DetallMovimentDelete.as_view(), name='detallMoviment_del'),
    path('detallsDeMoviments/inactivar/<int:id>',
         detallMoviment_inactivar, name='detallMoviment_inactivar'),
    
    
    path('formaPagaments/', FormaPagamentView.as_view(), name='formaPagament_list'),
    path('formaPagaments/new', FormaPagamentNew.as_view(), name='formaPagament_new'),
    path('formaPagaments/edit/<int:pk>',
         FormaPagamentEdit.as_view(), name='formaPagament_edit'),
    path('formaPagaments/delete/<int:pk>',
         FormaPagamentDelete.as_view(), name='formaPagament_del'),
    path('formaPagaments/inactivar/<int:id>',
         formaPagament_inactivar, name='formaPagament_inactivar'),
    
    
    path('caixes/', CaixaView.as_view(), name='caixa_list'),
    path('caixes/new', CaixaNew.as_view(), name='caixa_new'),
    path('caixes/edit/<int:pk>',
         CaixaEdit.as_view(), name='caixa_edit'),
    path('caixes/delete/<int:pk>',
         CaixaDelete.as_view(), name='caixa_del'),
    path('caixes/inactivar/<int:id>',
         caixa_inactivar, name='caixa_inactivar'),    
    path('caixes/usuaris/<int:id>',
         caixa_usuaris, name='caixa_usuaris'),
    path('caixes/usuarisestat/<int:id>',
         caixa_usuari_canvia_estat, name='caixa_canvia_estat'),               
]

bases/models.py
from django.db import models


from django_userforeignkey.models.fields import UserForeignKey


class ClasseBase(models.Model):
    estat = models.BooleanField(default=True)
    dataCreacio = models.DateTimeField(auto_now_add=True)
    dataModificacio = models.DateTimeField(auto_now=True)
    usuariCreacio = UserForeignKey(auto_user_add=True,related_name='+')
    usuariModificacio = UserForeignKey(auto_user=True,related_name='+')

    class Meta:
        abstract=True
        
        

mov/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy


from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, permission_required


from .models import GrupMoviment, SubgrupMoviment, DetallMoviment, FormaPagament, Caixa
from .forms import GrupMovimentForm, SubgrupMovimentForm, DetallMovimentForm, FormaPagamentForm, CaixaForm, CaixaFormUsuaris

from django.contrib.auth.models import User

from bases.views import SensePrivilegis

from django.template.defaulttags import register



#classes base
class ViewBaseNew(SuccessMessageMixin, SensePrivilegis,  generic.CreateView):
    context_object_name = "obj"
    #success_message="Registre creat correctament"
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    
    
class ViewBaseEdit(SuccessMessageMixin, SensePrivilegis,  generic.UpdateView):
    context_object_name = "obj"
    #success_message="Registre actualitzat correctament"
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
    
    

class GrupMovimentView( SensePrivilegis, generic.ListView):
    permission_required = "mov.view_grupmoviment"
    model = GrupMoviment
    template_name = "mov/grupMoviment_list.html"
    context_object_name = "obj"

    
class GrupMovimentNew(ViewBaseNew):
    permission_required="mov.add_grupmoviment"
    model=GrupMoviment
    template_name="mov/grupMoviment_form.html"
    form_class=GrupMovimentForm
    success_url=reverse_lazy("mov:grupMoviment_list")
    

    
class GrupMovimentEdit(ViewBaseEdit):
    permission_required="mov.change_grupmoviment"
    model=GrupMoviment
    template_name="mov/grupMoviment_form.html"
    form_class=GrupMovimentForm
    success_url=reverse_lazy("mov:grupMoviment_list")


class GrupMovimentDelete(SuccessMessageMixin, generic.DeleteView):
    permission_required="mov.delete_grupmoviment"
    model=GrupMoviment
    template_name='mov/cataleg_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("mov:grupMoviment_list")
    success_message="Grup de moviment eliminat correctament"
    
    
@login_required(login_url='/login/')
@permission_required('mov.change_grupmoviment', login_url='bases:sense_privilegis')
def grupMoviment_inactivar(request, id):
    grupMoviment = GrupMoviment.objects.filter(pk=id).first()
    contexto={}
    template_name="mov/grupMoviment_inactivar.html"
    if not grupMoviment:
        return redirect("mov:grupMoviment_list")
   
    if request.method=='GET':
        contexto={'obj':grupMoviment}
    if request.method=='POST':
        grupMoviment.estat=False
        grupMoviment.save()
        #messages.success(request, 'Grup de moviment desactivat')
        return redirect("mov:grupMoviment_list")
    return render(request,template_name,contexto)   







class SubgrupMovimentView( SensePrivilegis, generic.ListView):
    permission_required = "mov.view_subgrupmoviment"
    model = SubgrupMoviment
    template_name = "mov/subgrupMoviment_list.html"
    context_object_name = "obj"

    
class SubgrupMovimentNew(ViewBaseNew):
    permission_required="mov.add_subgrupmoviment"
    model=SubgrupMoviment
    template_name="mov/subgrupMoviment_form.html"
    form_class=SubgrupMovimentForm
    success_url=reverse_lazy("mov:subgrupMoviment_list")

    
class SubgrupMovimentEdit(ViewBaseEdit):
    permission_required="move.change_subgrupmoviment"
    model=SubgrupMoviment
    template_name="mov/subgrupMoviment_form.html"
    form_class=SubgrupMovimentForm
    success_url=reverse_lazy("mov:subgrupMoviment_list")


class SubgrupMovimentDelete(SuccessMessageMixin, generic.DeleteView):
    permission_required="mov.delete_subgrupmoviment"
    model=SubgrupMoviment
    template_name='mov/cataleg_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("mov:subgrupMoviment_list")
    success_message="Subgrup de moviment eliminat correctament"
    
    
@login_required(login_url='/login/')
@permission_required('mov.change_subgrupmoviment', login_url='bases:sense_privilegis')
def subgrupMoviment_inactivar(request, id):
    subgrupMoviment = SubgrupMoviment.objects.filter(pk=id).first()
    contexto={}
    template_name="mov/subgrupMoviment_inactivar.html"
    if not subgrupMoviment:
        return redirect("mov:subgrupMoviment_list")
   
    if request.method=='GET':
        contexto={'obj':subgrupMoviment}
    if request.method=='POST':
        subgrupMoviment.estat=False
        subgrupMoviment.save()
        #messages.success(request, 'Grup de moviment desactivat')
        return redirect("mov:subgrupMoviment_list")
    return render(request,template_name,contexto)   





class DetallMovimentView( SensePrivilegis, generic.ListView):
    permission_required = "mov.view_detallmoviment"
    model = DetallMoviment
    template_name = "mov/detallMoviment_list.html"
    context_object_name = "obj"

    
class DetallMovimentNew(ViewBaseNew):
    permission_required="mov.add_detallmoviment"
    model=DetallMoviment
    template_name="mov/detallMoviment_form.html"
    form_class=DetallMovimentForm
    success_url=reverse_lazy("mov:detallMoviment_list")
    
    def get_context_data(self, **kwargs):
        context = super(DetallMovimentNew, self).get_context_data(**kwargs)
        context["grupsMoviment"] = GrupMoviment.objects.all().order_by("descripcio")
        context["subgrupsMoviment"] = SubgrupMoviment.objects.all().order_by("descripcio")
        return context


class DetallMovimentEdit(ViewBaseEdit):
    permission_required="move.change_detallmoviment"
    model=DetallMoviment
    template_name="mov/detallMoviment_form.html"
    form_class=DetallMovimentForm
    success_url=reverse_lazy("mov:detallMoviment_list")
    
    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        context = super(DetallMovimentEdit, self).get_context_data(**kwargs)
        context["grupsMoviment"] = GrupMoviment.objects.all().order_by("descripcio")
        context["subgrupsMoviment"] = SubgrupMoviment.objects.all().order_by("descripcio")
        context["obj"] = DetallMoviment.objects.filter(pk=pk).first()
        return context


class DetallMovimentDelete(SuccessMessageMixin, generic.DeleteView):
    permission_required="mov.delete_detallmoviment"
    model=DetallMoviment
    template_name='mov/cataleg_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("mov:detallMoviment_list")
    success_message="Detall de moviment eliminat correctament"
    
    
@login_required(login_url='/login/')
@permission_required('mov.change_detallmoviment', login_url='bases:sense_privilegis')
def detallMoviment_inactivar(request, id):
    detallMoviment = DetallMoviment.objects.filter(pk=id).first()
    contexto={}
    template_name="mov/detallMoviment_inactivar.html"
    if not detallMoviment:
        return redirect("mov:detallMoviment_list")
   
    if request.method=='GET':
        contexto={'obj':detallMoviment}
    if request.method=='POST':
        detallMoviment.estat=False
        detallMoviment.save()
        #messages.success(request, 'Grup de moviment desactivat')
        return redirect("mov:detallMoviment_list")
    return render(request,template_name,contexto)   




class FormaPagamentView( SensePrivilegis, generic.ListView):
    permission_required = "mov.view_formapagament"
    model = FormaPagament
    template_name = "mov/formaPagament_list.html"
    context_object_name = "obj"

    
class FormaPagamentNew(ViewBaseNew):
    permission_required="mov.add_formapagament"
    model=FormaPagament
    template_name="mov/formaPagament_form.html"
    form_class=FormaPagamentForm
    success_url=reverse_lazy("mov:formaPagament_list")

    
class FormaPagamentEdit(ViewBaseEdit):
    permission_required="move.change_formapagament"
    model=FormaPagament
    template_name="mov/formaPagament_form.html"
    form_class=FormaPagamentForm
    success_url=reverse_lazy("mov:formaPagament_list")


class FormaPagamentDelete(SuccessMessageMixin, generic.DeleteView):
    permission_required="mov.delete_formapagament"
    model=FormaPagament
    template_name='mov/cataleg_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("mov:formaPagament_list")
    success_message="Forma de pagament correctament"
    
    
@login_required(login_url='/login/')
@permission_required('mov.change_formapagament', login_url='bases:sense_privilegis')
def formaPagament_inactivar(request, id):
    formaPagament = FormaPagament.objects.filter(pk=id).first()
    contexto={}
    template_name="mov/formaPagament_inactivar.html"
    if not formaPagament:
        return redirect("mov:formaPagament_list")
   
    if request.method=='GET':
        contexto={'obj':formaPagament}
    if request.method=='POST':
        formaPagament.estat=False
        formaPagament.save()
        #messages.success(request, 'Grup de moviment desactivat')
        return redirect("mov:formaPagament_list")
    return render(request,template_name,contexto)   






class CaixaView( SensePrivilegis, generic.ListView):
    permission_required = "mov.view_caixa"
    model = Caixa
    template_name = "mov/caixa_list.html"
    context_object_name = "obj"
    
    
class CaixaNew(ViewBaseNew):
    permission_required="mov.add_caixa"
    model=Caixa
    template_name="mov/caixa_form.html"
    form_class=CaixaForm
    success_url=reverse_lazy("mov:caixa_list")

    
class CaixaEdit(ViewBaseEdit):
    permission_required="mov.change_caixa"
    model=Caixa
    template_name="mov/caixa_form.html"
    form_class=CaixaForm
    success_url=reverse_lazy("mov:caixa_list")


class CaixaDelete(SuccessMessageMixin, generic.DeleteView):
    permission_required="mov.delete_caixa"
    model=Caixa
    template_name='mov/cataleg_del.html'
    context_object_name='obj'

mov/templates/mov/caixa_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Caixa</h6>
      <div class="dropdown no-arrow">
        <a onclick="return obrir_modal('{% url 'mov:caixa_new' %}')" href="#" class="btn btn-success btn-circle" role="button" ><i class="fa fa-plus"> </i></a>  
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hi ha caixes</div>
        {%else %}
        <table class="table table-striped table-hover">
            <thead>
            	<th>Descripci&oacute</th>
            	<th>Color</th>
            	<th>Banc</th>
                <!-- <th>Estat</th>-->
                <th>Activa usuari</th>
                <th>Data creaci&oacute</th>
                <th>Data modificaci&oacute</th>
                
                <th class="all">Accions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                	<td>{{item.descripcio}}</td>
                	<td>
                         <button disabled class="color" value="{{item.color}}" style="border: none;">&nbsp;&nbsp;&nbsp; </button>
				    </td>
				    <td>{{item.banc|yesno:"Sí,No" }}</td>
                    <!-- <td>{{item.estat|yesno:"Actiu,Inactiu" }}</td> -->
                    <td>{{item.usuaris|is_username:user.username|yesno:"Sí,No" }} </td>
                    <td>{{item.dataCreacio|date:"d/m/Y H:i:s"}}</td>
                    <td>{{item.dataModificacio|date:"d/m/Y H:i:s"}}</td>
                    <td>
                        <button class="btn btn-info btn-circle" onclick="return obrir_modal('{% url 'mov:caixa_edit' item.id %}')"><i class="far fa-edit"></i></button>
                        {% if item.usuaris|is_username:user.username %}
                        <button class="btn btn-danger btn-circle" onclick="return obrir_modal('{% url 'mov:caixa_canvia_estat' item.id %}')"><i class="fas fa-user-times"></i></button>
                        {% else %}
                        <button class="btn btn-success btn-circle" onclick="return obrir_modal('{% url 'mov:caixa_canvia_estat' item.id %}')"><i class="fas fa-user-check"></i></button>
                        {% endif %}  
                        <!--  <button class="btn btn-primary btn-circle" onclick="return obrir_modal('{% url 'mov:caixa_usuaris' item.id %}')"><i class="fas fa-users"></i></button>-->
                        <button class="btn btn-warning btn-circle" onclick="return obrir_modal('{% url 'mov:caixa_inactivar' item.id %}')"><i class="far fa-thumbs-down"></i></button>
                        <a href="{% url 'mov:caixa_del' item.id %}" class="btn btn-danger btn-circle" role="button" ><i class="far fa-trash-alt"> </i></a>  
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock page_content %}

{% block js_page %}
<script>
  //Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
  
  $('.color').colorPicker({
	}); 
</script>
{% endblock js_page %}

mov/templates/mov/cataleg_del.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Eliminar {{ obj.descripcio }}?</div>
                <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Sí, eliminar</button>
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo">Cancel·lar</span></a>
              </div>
              <div class="col-auto">
                <i class="fas fa-question-circle fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</form>
{% endblock page_content %}
{%block js_page %}
{% endblock js_page %}

mov/templates/mov/detallMoviment_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Detall de moviments</h6>
      <div class="dropdown no-arrow">
        <a onclick="return obrir_modal('{% url 'mov:detallMoviment_new' %}')" href="#" class="btn btn-success btn-circle" role="button" ><i class="fa fa-plus"> </i></a>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hi ha detall de moviments</div>
        {%else %}
        <table class="table table-striped table-hover">
            <thead>
            	<th>Grup</th>
            	<th>Subgrup</th>
                <th>Descripció</th>
                <th>Estat</th>
                <th>Data creació</th>
                <th>Data modificació</th>
                <th class="all">Accions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                	<td>{{item.subgrupMoviment.grupMoviment}}</td>
                	<td>{{item.subgrupMoviment}}</td>
                    <td>{{item.descripcio}}</td>
                    <td>{{item.estat|yesno:"Actiu,Inactiu" }}</td>
                    <td>{{item.dataCreacio|date:"d/m/Y H:i:s"}}</td>
                    <td>{{item.dataModificacio|date:"d/m/Y H:i:s"}}</td>
                    <td>
                        <button class="btn btn-info btn-circle" onclick="return obrir_modal('{% url 'mov:detallMoviment_edit' item.id %}')"><i class="far fa-edit"></i></button>  
                        <button class="btn btn-warning btn-circle" onclick="return obrir_modal('{% url 'mov:detallMoviment_inactivar' item.id %}')"><i class="far fa-thumbs-down"></i></button>
                        <a href="{% url 'mov:detallMoviment_del' item.id %}" class="btn btn-danger btn-circle" role="button" ><i class="far fa-trash-alt"> </i></a>  
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock page_content %}

{% block js_page %}
<script>
  //Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}

mov/templates/mov/formaPagament_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Forma de pagament</h6>
      <div class="dropdown no-arrow">
        <a onclick="return obrir_modal('{% url 'mov:formaPagament_new' %}')" href="#" class="btn btn-success btn-circle" role="button" ><i class="fa fa-plus"> </i></a>  
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hi ha formes de pagament</div>
        {%else %}
        <table class="table table-striped table-hover">
            <thead>
            	<th>Descripció</th>
                <th>Estat</th>
                <th>Data creació</th>
                <th>Data modificació</th>
                <th class="all">Accions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                	<td>{{item.descripcio}}</td>
                    <td>{{item.estat|yesno:"Actiu,Inactiu" }}</td>
                    <td>{{item.dataCreacio|date:"d/m/Y H:i:s"}}</td>
                    <td>{{item.dataModificacio|date:"d/m/Y H:i:s"}}</td>
                    <td>
                        <button class="btn btn-info btn-circle" onclick="return obrir_modal('{% url 'mov:formaPagament_edit' item.id %}')"><i class="far fa-edit"></i></button>  
                        <button class="btn btn-warning btn-circle" onclick="return obrir_modal('{% url 'mov:formaPagament_inactivar' item.id %}')"><i class="far fa-thumbs-down"></i></button>
                        <a href="{% url 'mov:formaPagament_del' item.id %}" class="btn btn-danger btn-circle" role="button" ><i class="far fa-trash-alt"> </i></a>  
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock page_content %}

{% block js_page %}
<script>
  //Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}

mov/templates/mov/grupMoviment_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Grups de moviments</h6>
      <div class="dropdown no-arrow">
        <a onclick="return obrir_modal('{% url 'mov:grupMoviment_new' %}')" href="#" class="btn btn-success btn-circle" role="button" ><i class="fa fa-plus"> </i></a>  
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hi ha grups de moviments</div>
        {%else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Descripció</th>
                <th>Color</th>
                <th>Estat</th>
                <th>Data creació</th>
                <th>Data modificació</th>
                <th class="all">Accions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                    <td>{{item.descripcio}}</td>
                    <td>
                         <button disabled class="color" value="{{item.color}}" style="border: none;">&nbsp;&nbsp;&nbsp; </button>
				    </td>
				    
                    <td>{{item.estat|yesno:"Actiu,Inactiu" }}</td>
                    <td>{{item.dataCreacio|date:"d/m/Y H:i:s"}}</td>
                    <td>{{item.dataModificacio|date:"d/m/Y H:i:s"}}</td>
                    <td>
                        <button class="btn btn-info btn-circle" onclick="return obrir_modal('{% url 'mov:grupMoviment_edit' item.id %}')"><i class="far fa-edit"></i></button>   
                        <button class="btn btn-warning btn-circle" onclick="return obrir_modal('{% url 'mov:grupMoviment_inactivar' item.id %}')"><i class="far fa-thumbs-down"></i></button>
                        <a href="{% url 'mov:grupMoviment_del' item.id %}" class="btn btn-danger btn-circle" role="button" ><i class="far fa-trash-alt"> </i></a>  
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock page_content %}

{% block js_page %}
<script>
  //Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
  
  $('.color').colorPicker({
	}); 
</script>
{% endblock js_page %}

mov/templates/mov/subgrupMoviment_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Subgrups de moviments</h6>
      <div class="dropdown no-arrow">
        <a onclick="return obrir_modal('{% url 'mov:subgrupMoviment_new' %}')" href="#" class="btn btn-success btn-circle" role="button" ><i class="fa fa-plus"> </i></a>  
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
        <div class="alert alert-info">No hi ha subgrups de moviments</div>
        {%else %}
        <table class="table table-striped table-hover">
            <thead>
            	<th>Grup</th>
                <th>Descripció</th>
                <th>Estat</th>
                <th>Data creació</th>
                <th>Data modificació</th>
                <th class="all">Accions</th>
            </thead>
            <tbody>
                {% for item in obj %}
                <tr>
                	<td>{{item.grupMoviment}}</td>
                    <td>{{item.descripcio}}</td>
                    <td>{{item.estat|yesno:"Actiu,Inactiu" }}</td>
                    <td>{{item.dataCreacio|date:"d/m/Y H:i:s"}}</td>
                    <td>{{item.dataModificacio|date:"d/m/Y H:i:s"}}</td>
                    <td>
                        <button class="btn btn-info btn-circle" onclick="return obrir_modal('{% url 'mov:subgrupMoviment_edit' item.id %}')"><i class="far fa-edit"></i></button>  
                        <button class="btn btn-warning btn-circle" onclick="return obrir_modal('{% url 'mov:subgrupMoviment_inactivar' item.id %}')"><i class="far fa-thumbs-down"></i></button>
                        <a href="{% url 'mov:subgrupMoviment_del' item.id %}" class="btn btn-danger btn-circle" role="button" ><i class="far fa-trash-alt"> </i></a>  
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock page_content %}

{% block js_page %}
<script>
  //Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock js_page %}