administracio/urls.py
from django.urls import path

from .views import usuari_edit

urlpatterns = [
    path('usuari/edit/<int:id>',
         usuari_edit, name='usuari_edit'),
    
]

financesDom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('mov/', include(('mov.urls', 'mov'), namespace='mov')),
    path('moviments/', include(('moviments.urls', 'moviments'), namespace='moviments')),
    path('admin/', admin.site.urls),
    path('administracio/', include(('administracio.urls', 'mov'), namespace='administracio')),
]

mov/urls.py
from django.urls import path
#from django.contrib import admin

from .views import GrupMovimentView, GrupMovimentNew, GrupMovimentEdit, GrupMovimentDelete, grupMoviment_inactivar, \
SubgrupMovimentView, SubgrupMovimentNew, SubgrupMovimentEdit, SubgrupMovimentDelete, subgrupMoviment_inactivar, \
DetallMovimentView, DetallMovimentNew, DetallMovimentEdit, DetallMovimentDelete, detallMoviment_inactivar,  \
FormaPagamentView, FormaPagamentNew, FormaPagamentEdit, FormaPagamentDelete, formaPagament_inactivar, \
CaixaView, CaixaNew, CaixaEdit, CaixaDelete, caixa_inactivar, caixa_usuaris, caixa_usuari_canvia_estat


urlpatterns = [
    path('grupsDeMoviments/', GrupMovimentView.as_view(), name='grupMoviment_list'),
    path('grupsDeMoviments/new', GrupMovimentNew.as_view(), name='grupMoviment_new'),
    path('grupsDeMoviments/edit/<int:pk>',
         GrupMovimentEdit.as_view(), name='grupMoviment_edit'),
    path('grupsDeMoviments/delete/<int:pk>',
         GrupMovimentDelete.as_view(), name='grupMoviment_del'),
    path('grupsDeMoviments/inactivar/<int:id>',
         grupMoviment_inactivar, name='grupMoviment_inactivar'),
    
    
    path('subgrupsDeMoviments/', SubgrupMovimentView.as_view(), name='subgrupMoviment_list'),
    path('subgrupsDeMoviments/new', SubgrupMovimentNew.as_view(), name='subgrupMoviment_new'),
    path('subgrupsDeMoviments/edit/<int:pk>',
         SubgrupMovimentEdit.as_view(), name='subgrupMoviment_edit'),
    path('subgrupsDeMoviments/delete/<int:pk>',
         SubgrupMovimentDelete.as_view(), name='subgrupMoviment_del'),
    path('subgrupsDeMoviments/inactivar/<int:id>',
         subgrupMoviment_inactivar, name='subgrupMoviment_inactivar'),
    
    
    path('detallsDeMoviments/', DetallMovimentView.as_view(), name='detallMoviment_list'),
    path('detallsDeMoviments/new', DetallMovimentNew.as_view(), name='detallMoviment_new'),
    path('detallsDeMoviments/edit/<int:pk>',
         DetallMovimentEdit.as_view(), name='detallMoviment_edit'),
    path('detallsDeMoviments/delete/<int:pk>',
         DetallMovimentDelete.as_view(), name='detallMoviment_del'),
    path('detallsDeMoviments/inactivar/<int:id>',
         detallMoviment_inactivar, name='detallMoviment_inactivar'),
    
    
    path('formaPagaments/', FormaPagamentView.as_view(), name='formaPagament_list'),
    path('formaPagaments/new', FormaPagamentNew.as_view(), name='formaPagament_new'),
    path('formaPagaments/edit/<int:pk>',
         FormaPagamentEdit.as_view(), name='formaPagament_edit'),
    path('formaPagaments/delete/<int:pk>',
         FormaPagamentDelete.as_view(), name='formaPagament_del'),
    path('formaPagaments/inactivar/<int:id>',
         formaPagament_inactivar, name='formaPagament_inactivar'),
    
    
    path('caixes/', CaixaView.as_view(), name='caixa_list'),
    path('caixes/new', CaixaNew.as_view(), name='caixa_new'),
    path('caixes/edit/<int:pk>',
         CaixaEdit.as_view(), name='caixa_edit'),
    path('caixes/delete/<int:pk>',
         CaixaDelete.as_view(), name='caixa_del'),
    path('caixes/inactivar/<int:id>',
         caixa_inactivar, name='caixa_inactivar'),    
    path('caixes/usuaris/<int:id>',
         caixa_usuaris, name='caixa_usuaris'),
    path('caixes/usuarisestat/<int:id>',
         caixa_usuari_canvia_estat, name='caixa_canvia_estat'),               
]

administracio/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


from bases.models import ClasseBase
#from idlelib.iomenu import blank_re
       
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class UserExt( ClasseBase):
    #user = models.OneToOneField(User, on_delete=models.PROTECT)
    avatar = models.ImageField(upload_to=user_directory_path)
    
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserExt.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userext.save()
    
    

administracio/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from .models import UserExt

@login_required(login_url='/login/')
def usuari_edit(request, id):
    usuari = User.objects.filter(pk=id).first()
    usuariExt = UserExt.objects.filter(pk=usuari.userext.id).first()
    
    context={}
    template_name="administracio/usuari_edit.html"
    
    if not usuari:
        return redirect("bases:sense_privilegis")
   
    if request.method=='GET':
        if usuari.username!=str(request.user):
            return redirect("bases:sense_privilegis")
        context={'obj':usuari, 'ext':usuariExt}
    if request.method=='POST':
        data = request.POST.copy()
        usuariExt.avatar = data.get('avatar')
        #usuari.set_password(data.get('password'))
        usuari.save()
        usuariExt.save()
        return redirect("moviments:moviment_dash")
    return render(request,template_name,context)   

administracio/templates/administracio/usuari_edit.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form method="POST" role="form" class="form-inline" action="{% url 'administracio:usuari_edit' obj.pk %}" >
        {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
		                <div class="row no-gutters align-items-center">
		                    <div class="col mr-2">
		                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
		                            Editar usuari
		                        </div>
		                        <div class="dropdown-divider"></div>
		                        <div class="row">
		                            <div class="col-10">
		                                <div class="input-group">
		                                    <input type="text" name="nomusuari" maxlength="100" class="form-control"
		                                        required id="id_nomusuari" placeholder="nomusuari;" disabled value="{{ obj.username}}">
		                                </div>
		                            </div>
		
		
									<!-- <div class="col-10">
		                                <div class="input-group">
		                                    <input type="password" name="password" maxlength="100" class="form-control"
		                                        required id="id_password" placeholder="password">
		                                </div>
		                            </div>-->
		                            
		                            <div class="col-10">
		                                <div class="input-group">
		                                    <input type="text" name="avatar" maxlength="100" class="form-control"
		                                        required id="id_avatar" placeholder="avatar" value="{{ext.avatar}}">
		                                </div>
		                            </div>
		                            
		                        </div>
		                        <div class="dropdown-divider"></div>
		                        <div class="row">
		                            <div class="col">
		                                <button type="submit" class="btn btn-danger">
		                                    <span class="fa fa-save"></span> Salvar </button>
		                                <a href="#" onclick="tancar_modal()" class="btn btn-success"><span class="fa fa-undo"> Cancel&middot;lar</span> </a>
		                                </button>
		                            </div>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</form>
	</div>
</div>


<script>
$(function() {

    var url = $("form").attr("action");
    var token = jQuery("[name=csrfmiddlewaretoken]").val();

    $("form").submit(function(e){
        e.preventDefault();
        // alert(token);
        var formData = $("form").serializeArray();
        // console.log(formData);
        $.ajax({
            url:url,
            method:"POST",
            headers: {'X-CSRFToken': token },
            data: formData
        })
        .done(function(r,textStatus,xhr){
            if(xhr.status=200){
                location.reload(true);
            }
            else{
				mensaje(textStatus);
            }
        }).fail(function (error) {
        	mensaje(error.responseText, 'error');
        });
    });
});
</script>